[package]
name = "core_deno"
version = "0.1.0"
edition = "2021"

[dependencies]
gveditor-core-api  = { path = "../core_api"}
async-trait = "0.1.52"

[dev-dependencies]
tokio = { version = "1.14.0", features = ["rt-multi-thread", "macros", "sync"]}