[package]
name = "core_deno"
version = "0.1.0"
edition = "2021"

[dependencies]
gveditor-core-api  = { path = "../core_api"}
deno_core = "0.119.0"
deno_runtime = "0.45.0"
tokio = { version = "1.14.0", features = ["rt-multi-thread", "macros", "sync", "time"]}