image: gitpod/workspace-full-vnc

tasks:
  - name: Install packages
    init: sudo apt update && sudo apt install libwebkit2gtk-4.0-dev \
      build-essential \
      curl \
      wget \
      libssl-dev \
      libgtk-3-dev \
      libappindicator3-dev \
      patchelf \
      librsvg2-dev
    env:
      DEBIAN_FRONTEND: noninteractive
  - name: Install tauri
    init: cargo install tauri-cli --git https://github.com/tauri-apps/tauri --branch tmp/pin-clap
  - name: Compile git extension
    init: cd extensions/git && cargo build
  - name: Install dependencies
    init: yarn

vscode:
  extensions:
    - rust-lang.rust
