osx_image: xcode8.4 # 

dist: trusty # 
sudo: required

language: node_js
node_js: '8'

os:
  - linux
  - osx
  - windows
  
branches:
    except:
      - master

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: 
    - Graviton-1.0.2.exe
    - Graviton-1.0.2.dmg
    - Graviton-1.0.2-amd64.deb
  skip_cleanup: true
  draft: true

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf $HOME/.cache/electron-builder/wine; fi
# These commands are executed before the scripts are executed
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install rpm; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install wine; fi
  - npm install

script:
  - echo "BUILDING"
  - npm run build
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm run build:win32; fi
  - ls dist