osx_image: xcode8.4 # 

dist: trusty # 
sudo: required

language: node_js
node_js: '8'

os:
  - linux
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: ./*
  skip_cleanup: true
  draft: true

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf $HOME/.cache/electron-builder/wine; fi
# These commands are executed before the scripts are executed

before_install:
  - f [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    wget https://dl.winehq.org/wine-builds/Release.key
    sudo apt-key add Release.key
    sudo apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu/'
    sudo apt-get update;
    sudo apt-get install wine1.8 winetricks;
    fi;

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      sudo apt-get install rpm;
    fi
  - npm install

script:
  - echo "BUILDING"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      npm run build:win;
      npm run build; 
    fi
  - ls dist