[workspace]
resolver = "2"
members = [
   "core",
   "core_api",
   "core_deno",
   "desktop/src-tauri",
   "extensions/git",
   "extensions/typescript-lsp",
   "server"
]

[profile.release]
lto = true
opt-level = "z"