[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.watch_web_components]
script = "yarn workspace @gveditor/web_components dev"

[tasks.serve_demo_web]
script = "yarn workspace @gveditor/web dev"

[tasks.desktop_demo]
command = "cargo"
args = ["run", "--package", "desktop"]

[tasks.demo]
run_task = [
    { name = ["serve_demo_web", "watch_web_components", "desktop_demo"], parallel = true }
]