[package]
name = "gveditor-core-api"
version = "0.1.0"
description = "Graviton Core API"
authors = ["Marc Espín Sanz"]
edition = "2021"
readme = "readme.md"
repository = "https://github.com/Graviton-Code-Editor/Graviton-App/tree/graviton-rewrite"
homepage = "https://github.com/Graviton-Code-Editor/Graviton-App/tree/graviton-rewrite"
license = "MIT"

[dependencies]
