name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Installing nodejs dependencies
        run: yarn
      - name: Running unit tests
        run: yarn test
