name: CI

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Installing nodejs dependencies
        run: yarn

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Build web_components
        run: yarn --cwd web_components run build

      - name: Build web
        run: yarn --cwd web run build

      - name: Install linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update && sudo apt install libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          libappindicator3-dev \
          patchelf \
          librsvg2-dev
       
      - name: Install MacOS dependencies
        if: runner.os == 'macOS'
        run: brew install gcc

      - name: Install nextest (test runner for rust)
        run: cargo install cargo-nextest

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Running unit tests
        run: yarn test
