name: CI

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Installing Node dependencies
        run: pnpm install

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Build web
        run: pnpm run --filter web build

      - name: Install linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update && sudo apt install libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          libappindicator3-dev \
          patchelf \
          librsvg2-dev
       
      - name: Install MacOS dependencies
        if: runner.os == 'macOS'
        run: brew install gcc

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest

      - name: Running rust tests
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run

      - name: Running web tests
        run: pnpm run --filter web test
