name: Node CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest , macos-latest]
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing dependencies
      run: yarn
    - name: Building
      run: |
        yarn build:tasks
        yarn build:webpack
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Running unit tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: npm run test:mocha
    - name : Building for RPM
      if: ${{ runner.os == 'Linux' }}
      run: yarn build:electron --info platform="rpm"
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}